# Generated by Django 2.1.1 on 2018-10-10 17:49

import bets.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('wager', models.TextField()),
                ('bettor', models.CharField(max_length=100)),
                ('opponent', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField(verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='bet made date')),
                ('outcome', models.CharField(choices=[(bets.enums.BetResultChoice('Opponent Lost'), 'Opponent Lost'), (bets.enums.BetResultChoice('Bettor Lost'), 'Bettor Lost'), (bets.enums.BetResultChoice('Everyone Lost(tied)'), 'Everyone Lost(tied)')], max_length=1)),
            ],
        ),
    ]
