# Generated by Django 2.1.1 on 2018-10-10 18:00

import bets.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='state',
            field=models.CharField(choices=[(bets.enums.BetStateChoice('Completed'), 'Completed'), (bets.enums.BetStateChoice('Open'), 'Open'), (bets.enums.BetStateChoice('Abandoned'), 'Abandoned')], default=bets.enums.BetStateChoice('Open'), max_length=1),
        ),
        migrations.AlterField(
            model_name='bet',
            name='outcome',
            field=models.CharField(blank=True, choices=[(bets.enums.BetResultChoice('Opponent Lost'), 'Opponent Lost'), (bets.enums.BetResultChoice('Bettor Lost'), 'Bettor Lost'), (bets.enums.BetResultChoice('Everyone Lost(tied)'), 'Everyone Lost(tied)')], max_length=1),
        ),
    ]
