# Generated by Django 2.1.3 on 2018-11-13 19:31

import bets.enums
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='outcome',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=bets.enums.BetResultChoice, max_length=1, null=True),
        ),
    ]
